# Welcome :)
## Let's first implement Linear regression using Scikit-learn library

## 1) import libraries and data

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
x,y = load_diabetes(return_X_y=True)


### Explore your data ---> visit [The documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)

In [3]:
print("dimensions of the training examples are ", x.shape) #----> (no. of examples, no. of features)
print("dimensions of the labels are ", y.shape) #---> single label for each training example  (no. of training examples,1)


dimensions of the training examples are  (442, 10)
dimensions of the labels are  (442,)


### Import the model class

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
model = LinearRegression()

In [6]:
model.fit(x,y) # Fitting the model means search for the best paramters based on the data

LinearRegression()

### now we have a model ready for predictions

In [7]:
example = np.expand_dims(x[0],0) # The model expects something with dimensions (number ,no. of features)
print( "shape before expanding",x[0].shape)
print( "shape after expanding",example.shape)

shape before expanding (10,)
shape after expanding (1, 10)


In [8]:
pred = model.predict(example)
print("our model predicted {} ".format(pred))
print("But the real value was {}".format(y[0]))

our model predicted [206.11667725] 
But the real value was 151.0


In [11]:
print("The 10 weights are :",model.coef_) # 10 weights because we have 10 features for each training example
print("the bias is : ",model.intercept_)

The 10 weights are : [ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]
the bias is :  152.13348416289597


## Now let's build the model from scratch 

## note the shapes
## x -- > (m,n)
## y -- > (m,1)
## w -- > (1,n)
## b -- > (1,1)



In [12]:
def init_weights(x):
    m,n = x.shape
    w = dict()
    w[0] = np.zeros((1,n))
    w[1] = np.zeros((1,1))
    return w

In [13]:
def forward(w,x):
    out = np.dot(w[0],x.T) + w[1]
    return out
    

In [14]:
def cost(out,x,y):
    m,n = x.shape
                                    
    J = 1/(2*m) * (np.sum(np.square(y - out),keepdims=True))
    return J
    

In [15]:
def update_weights(out,x,y,lr,w):
    dj = dict()
    m = x.shape[0]
    dj[0] = - 1/m * np.dot((y - out),x)      #()(m,n)
    dj[1] = - 1/m * np.sum((y-out)) 
    w[0] = w[0] - lr * dj[0]
    w[1] = w[1] - lr * dj[1]
    
    return w


In [16]:
def fit(x,y,w,epochs,lr=0.001):
    for i in range(epochs):
        out = forward(w,x)
        J = cost(out,x,y)
        w = update_weights(out,x,y,lr,w)
        
    

In [17]:
w = init_weights(x)
fit(x,y,w,epochs=1000,lr=0.1)

In [18]:
w

{0: array([[  40.03843741,   -5.80476007,  162.28636313,  117.37340334,
           38.41629773,   24.90309153, -100.43159014,   99.58161206,
          149.32726468,   92.21994613]]),
 1: array([[152.13348416]])}

In [19]:
forward(w,example)

array([[168.82351966]])

In [20]:
ex2 = x[1].reshape(1,-1)
print(model.predict(ex2))
print(forward(w,ex2))


[68.07103297]
[[109.95887833]]


In [21]:
fit(x,y,w,epochs=5000,lr=0.1)

# Let's solve the same problem using a simple neural network
## single neuron 
## Implementation in PyTorch

In [22]:
import torch
import torch.nn as nn
import torch.functional as f
from torch import optim

In [47]:
class RegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10,16000)
        self.fc2  = nn.Linear(16000,1)
        self.optim = optim.SGD(params=self.parameters(),lr=0.1,momentum=0.9)
        self.loss = nn.MSELoss()
    def forward(self,x):
        x = torch.tensor(x,dtype=torch.float32)
        out = self.fc1(x)
        out = self.fc2(out)
        return out

In [48]:
regression_model = RegressionModel()

In [25]:
y_tensor.shape
out.shape

NameError: name 'y_tensor' is not defined

In [ ]:
epochs = 5000
y_tensor = torch.tensor(y,dtype=torch.float32)
for i in range(epochs):
    out = regression_model.forward(x)
    
    loss = regression_model.loss(y_tensor.view(-1,1),out)
    if i % 100 == 0:
        print("The current loss now at epoch {} is {} ".format(i,loss))
    regression_model.optim.zero_grad()
    loss.backward()
    regression_model.optim.step()

    

The current loss now at epoch 0 is 29122.14453125 
The current loss now at epoch 100 is nan 
The current loss now at epoch 200 is nan 
The current loss now at epoch 300 is nan 
The current loss now at epoch 400 is nan 
The current loss now at epoch 500 is nan 
The current loss now at epoch 600 is nan 
The current loss now at epoch 700 is nan 
The current loss now at epoch 800 is nan 
The current loss now at epoch 900 is nan 
The current loss now at epoch 1000 is nan 
The current loss now at epoch 1100 is nan 
The current loss now at epoch 1200 is nan 
The current loss now at epoch 1300 is nan 
The current loss now at epoch 1400 is nan 
The current loss now at epoch 1500 is nan 
The current loss now at epoch 1600 is nan 
The current loss now at epoch 1700 is nan 
The current loss now at epoch 1800 is nan 
The current loss now at epoch 1900 is nan 
The current loss now at epoch 2000 is nan 
The current loss now at epoch 2100 is nan 
The current loss now at epoch 2200 is nan 
The current 

In [95]:
x.shape

(442, 10)

In [27]:
for i in regression_model.fc1.weight:
    print(i)
    

tensor([  -7.0305, -236.5969,  527.6198,  321.8304, -163.7077,  -26.2407,
        -174.9734,  105.2628,  514.8530,   69.7730], grad_fn=<UnbindBackward0>)


In [28]:
regression_model.fc1.bias

Parameter containing:
tensor([152.1335], requires_grad=True)

# Implementation in TensorFlow

In [ ]:
import tensorflow as tf 
from tensorflow.keras import layers,models
from tensorflow.keras.optimizers import SGD, Adam

In [135]:
tf_model = models.Sequential()

In [ ]:
tf_model.add(layers.Dense(1,input_shape=(10,)))

In [136]:
tf_model.add(layers.Dense(1,input_shape=(10,)))

In [137]:
tf_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 11        
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


In [143]:
tf_model.compile(optimizer=Adam(learning_rate=0.1),loss='MeanSquaredError',metrics=['MeanSquaredError'])

In [139]:
%load_ext tensorboard

In [140]:

tb_callback = tf.keras.callbacks.TensorBoard(log_dir=r'logs/AI_session_2',histogram_freq=1)

In [144]:
tf_model.fit(x,y,callbacks=tb_callback,epochs=1000)

Epoch 1/1000
14/14 [==============================] - 1s 6ms/step - loss: 24618.6152 - mean_squared_error: 24618.6152
Epoch 2/1000
14/14 [==============================] - 0s 2ms/step - loss: 24208.5703 - mean_squared_error: 24208.5703
Epoch 3/1000
14/14 [==============================] - 0s 2ms/step - loss: 23812.9043 - mean_squared_error: 23812.9043
Epoch 4/1000
14/14 [==============================] - 0s 2ms/step - loss: 23423.3418 - mean_squared_error: 23423.3418
Epoch 5/1000
14/14 [==============================] - 0s 2ms/step - loss: 23029.0254 - mean_squared_error: 23029.0254
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 22649.2422 - mean_squared_error: 22649.2422
Epoch 7/1000
14/14 [==============================] - 0s 2ms/step - loss: 22274.4980 - mean_squared_error: 22274.4980
Epoch 8/1000
14/14 [==============================] - 0s 2ms/step - loss: 21904.1523 - mean_squared_error: 21904.1523
Epoch 9/1000
14/14 [==============================] - 0s

14/14 [==============================] - 0s 2ms/step - loss: 4089.6704 - mean_squared_error: 4089.6704
Epoch 137/1000
14/14 [==============================] - 0s 2ms/step - loss: 4069.8840 - mean_squared_error: 4069.8843
Epoch 138/1000
14/14 [==============================] - 0s 1ms/step - loss: 4051.7810 - mean_squared_error: 4051.7810
Epoch 139/1000
14/14 [==============================] - 0s 1ms/step - loss: 4032.6560 - mean_squared_error: 4032.6560
Epoch 140/1000
14/14 [==============================] - 0s 1ms/step - loss: 4014.5061 - mean_squared_error: 4014.5061
Epoch 141/1000
14/14 [==============================] - 0s 2ms/step - loss: 3996.8613 - mean_squared_error: 3996.8613
Epoch 142/1000
14/14 [==============================] - 0s 1ms/step - loss: 3980.6936 - mean_squared_error: 3980.6936
Epoch 143/1000
14/14 [==============================] - 0s 1ms/step - loss: 3963.4814 - mean_squared_error: 3963.4814
Epoch 144/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 3210.6272 - mean_squared_error: 3210.6272
Epoch 275/1000
14/14 [==============================] - 0s 2ms/step - loss: 3207.8252 - mean_squared_error: 3207.8252
Epoch 276/1000
14/14 [==============================] - 0s 2ms/step - loss: 3205.2012 - mean_squared_error: 3205.2012
Epoch 277/1000
14/14 [==============================] - 0s 2ms/step - loss: 3202.7197 - mean_squared_error: 3202.7197
Epoch 278/1000
14/14 [==============================] - 0s 2ms/step - loss: 3200.3494 - mean_squared_error: 3200.3494
Epoch 279/1000
14/14 [==============================] - 0s 2ms/step - loss: 3197.5015 - mean_squared_error: 3197.5015
Epoch 280/1000
14/14 [==============================] - 0s 2ms/step - loss: 3194.9575 - mean_squared_error: 3194.9575
Epoch 281/1000
14/14 [==============================] - 0s 2ms/step - loss: 3192.4954 - mean_squared_error: 3192.4954
Epoch 282/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 3066.0266 - mean_squared_error: 3066.0266
Epoch 344/1000
14/14 [==============================] - 0s 2ms/step - loss: 3064.4905 - mean_squared_error: 3064.4905
Epoch 345/1000
14/14 [==============================] - 0s 2ms/step - loss: 3062.8076 - mean_squared_error: 3062.8076
Epoch 346/1000
14/14 [==============================] - 0s 2ms/step - loss: 3061.9338 - mean_squared_error: 3061.9338
Epoch 347/1000
14/14 [==============================] - 0s 2ms/step - loss: 3059.8381 - mean_squared_error: 3059.8381
Epoch 348/1000
14/14 [==============================] - 0s 1ms/step - loss: 3058.1272 - mean_squared_error: 3058.1272
Epoch 349/1000
14/14 [==============================] - 0s 2ms/step - loss: 3056.6003 - mean_squared_error: 3056.6003
Epoch 350/1000
14/14 [==============================] - 0s 2ms/step - loss: 3055.1970 - mean_squared_error: 3055.1970
Epoch 351/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 2933.6614 - mean_squared_error: 2933.6614
Epoch 481/1000
14/14 [==============================] - 0s 2ms/step - loss: 2932.9753 - mean_squared_error: 2932.9753
Epoch 482/1000
14/14 [==============================] - 0s 1ms/step - loss: 2932.5520 - mean_squared_error: 2932.5520
Epoch 483/1000
14/14 [==============================] - 0s 2ms/step - loss: 2932.0186 - mean_squared_error: 2932.0186
Epoch 484/1000
14/14 [==============================] - 0s 1ms/step - loss: 2931.7803 - mean_squared_error: 2931.7803
Epoch 485/1000
14/14 [==============================] - 0s 1ms/step - loss: 2931.0479 - mean_squared_error: 2931.0479
Epoch 486/1000
14/14 [==============================] - 0s 1ms/step - loss: 2930.7021 - mean_squared_error: 2930.7021
Epoch 487/1000
14/14 [==============================] - 0s 1ms/step - loss: 2930.3430 - mean_squared_error: 2930.3430
Epoch 488/1000
14/14 [==============================] - 0s 1ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 2895.5735 - mean_squared_error: 2895.5735
Epoch 618/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.6875 - mean_squared_error: 2895.6875
Epoch 619/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.4211 - mean_squared_error: 2895.4211
Epoch 620/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.5625 - mean_squared_error: 2895.5625
Epoch 621/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.2786 - mean_squared_error: 2895.2786
Epoch 622/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.0764 - mean_squared_error: 2895.0764
Epoch 623/1000
14/14 [==============================] - 0s 2ms/step - loss: 2894.8853 - mean_squared_error: 2894.8853
Epoch 624/1000
14/14 [==============================] - 0s 2ms/step - loss: 2895.0596 - mean_squared_error: 2895.0596
Epoch 625/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 1ms/step - loss: 2889.3479 - mean_squared_error: 2889.3479
Epoch 686/1000
14/14 [==============================] - 0s 1ms/step - loss: 2889.3396 - mean_squared_error: 2889.3396
Epoch 687/1000
14/14 [==============================] - 0s 1ms/step - loss: 2889.2700 - mean_squared_error: 2889.2700
Epoch 688/1000
14/14 [==============================] - 0s 2ms/step - loss: 2889.5022 - mean_squared_error: 2889.5022
Epoch 689/1000
14/14 [==============================] - 0s 2ms/step - loss: 2889.0459 - mean_squared_error: 2889.0459
Epoch 690/1000
14/14 [==============================] - 0s 2ms/step - loss: 2889.0146 - mean_squared_error: 2889.0146
Epoch 691/1000
14/14 [==============================] - 0s 2ms/step - loss: 2889.3701 - mean_squared_error: 2889.3701
Epoch 692/1000
14/14 [==============================] - 0s 2ms/step - loss: 2889.2786 - mean_squared_error: 2889.2786
Epoch 693/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 2886.2463 - mean_squared_error: 2886.2463
Epoch 755/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.4021 - mean_squared_error: 2886.4021
Epoch 756/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.0322 - mean_squared_error: 2886.0322
Epoch 757/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.3315 - mean_squared_error: 2886.3315
Epoch 758/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.1548 - mean_squared_error: 2886.1548
Epoch 759/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.5820 - mean_squared_error: 2886.5820
Epoch 760/1000
14/14 [==============================] - 0s 2ms/step - loss: 2886.1138 - mean_squared_error: 2886.1138
Epoch 761/1000
14/14 [==============================] - 0s 2ms/step - loss: 2885.9885 - mean_squared_error: 2885.9885
Epoch 762/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 2884.4102 - mean_squared_error: 2884.4102
Epoch 824/1000
14/14 [==============================] - 0s 2ms/step - loss: 2884.4441 - mean_squared_error: 2884.4441
Epoch 825/1000
14/14 [==============================] - 0s 2ms/step - loss: 2884.3601 - mean_squared_error: 2884.3601
Epoch 826/1000
14/14 [==============================] - 0s 1ms/step - loss: 2884.5510 - mean_squared_error: 2884.5510
Epoch 827/1000
14/14 [==============================] - 0s 2ms/step - loss: 2884.3279 - mean_squared_error: 2884.3279
Epoch 828/1000
14/14 [==============================] - 0s 1ms/step - loss: 2884.4434 - mean_squared_error: 2884.4434
Epoch 829/1000
14/14 [==============================] - 0s 1ms/step - loss: 2884.2400 - mean_squared_error: 2884.2400
Epoch 830/1000
14/14 [==============================] - 0s 2ms/step - loss: 2884.4048 - mean_squared_error: 2884.4048
Epoch 831/1000
14/14 [==============================] - 0s 2ms/step - l

14/14 [==============================] - 0s 2ms/step - loss: 2882.7896 - mean_squared_error: 2882.7896
Epoch 961/1000
14/14 [==============================] - 0s 1ms/step - loss: 2883.0310 - mean_squared_error: 2883.0310
Epoch 962/1000
14/14 [==============================] - 0s 2ms/step - loss: 2882.7900 - mean_squared_error: 2882.7900
Epoch 963/1000
14/14 [==============================] - 0s 2ms/step - loss: 2882.8931 - mean_squared_error: 2882.8931
Epoch 964/1000
14/14 [==============================] - 0s 1ms/step - loss: 2882.9993 - mean_squared_error: 2882.9993
Epoch 965/1000
14/14 [==============================] - ETA: 0s - loss: 2016.7534 - mean_squared_error: 2016.75 - 0s 1ms/step - loss: 2882.6106 - mean_squared_error: 2882.6106
Epoch 966/1000
14/14 [==============================] - 0s 1ms/step - loss: 2882.8809 - mean_squared_error: 2882.8809
Epoch 967/1000
14/14 [==============================] - 0s 2ms/step - loss: 2882.9275 - mean_squared_error: 2882.9275
Epoch 968/100

In [145]:
tf_model.weights

[<tf.Variable 'dense/kernel:0' shape=(10, 1) dtype=float32, numpy=
 array([[  -6.104809],
        [-242.17064 ],
        [ 520.0777  ],
        [ 326.89047 ],
        [ -46.72725 ],
        [-130.94655 ],
        [-217.38963 ],
        [ 119.02975 ],
        [ 454.3668  ],
        [  80.42992 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([152.27803], dtype=float32)>]

In [102]:
from sklearn.metrics import mean_squared_error
preds = regression_model.forward(x)


In [148]:
m,n = x.shape

In [151]:
w[0].shape

(1, 10)

In [168]:
y=y.reshape(-1,1)

In [181]:
y= y.reshape(-1,)

## For loops are Slow......

In [183]:
%%time
mse = 0
for j in range(m):
    h=0
    for i in range(n):
        h += w[0][0,i] * x[j,i]
    h += w[1]
    #print(h)
        
    mse += (y[j] - h)**2

mse = mse/(2*m)
print(mse)

[[1459.67511971]]
Wall time: 8.97 ms


In [182]:
%%time
out=forward(w,x)

cost(out,x,y)

Wall time: 0 ns


array([[1459.67511971]])

In [157]:
np.dot(w[0],x[0].reshape(10,1))

array([[45.37031339]])

In [1]:
import gym
env = gym.make("MountainCar-v0")
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()

In [2]:
from stable_baselines3 import DQN


In [3]:
model = DQN('MlpPolicy',env=env)

In [10]:
model.learn(total_timesteps=100000)

In [ ]:
obs = env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()

In [ ]:
env.reset()

In [1]:
import torch

In [6]:
t = torch.rand(size = (4,5),requires_grad = True)

In [13]:
t

tensor([[0.0682, 0.7253, 0.8534, 0.1551, 0.5445],
        [0.5727, 0.3471, 0.2407, 0.3087, 0.4518],
        [0.5476, 0.5541, 0.3467, 0.6483, 0.1363],
        [0.4152, 0.3464, 0.1287, 0.1539, 0.2158]], requires_grad=True)

In [14]:
a = t*4

In [16]:
a.sum()

tensor(31.0425, grad_fn=<SumBackward0>)

In [18]:
a.sum().backward()

In [20]:
t.grad

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])